portaria-eb:
  build: ./web
  ports:
    - "8081:8080"
  links:
    - mysql-db

mysql-db:
  build: ./db
  ports:
    - "3306:3306"
  volumes_from:
    - mysql-db-data

mysql-db-data:
  image: cogniteev/echo
  command: echo 'Data Container for MySql'
  volumes:
    - /home/italo/Documentos/Dependencies/data
