app-web:
  build: ./web
  ports:
    - "8081:8080"
  links:
    - app-db

app-db:
  build: ./db
  ports:
    - "3306:3306"
  volumes_from:
    - app-db-data

app-db-data:
  image: cogniteev/echo
  command: echo 'Data Container for MySql'
  volumes:
    - /var/lib/mysql/data
